import pathlib

path = pathlib.Path('/opt/attendance-system/docs/ATTENDANCE_SYSTEM_AUDIT_REPORT.md')

lines = [
    '# ATTENDANCE SYSTEM AUDIT REPORT\n',
    '\n',
    '**稽核日期：** 2026-03-13  \n',
    '**稽核類型：** SCAN ONLY — 不修改任何程式碼  \n',
    '**稽核範圍：** `backend/app/modules/attendance`、`backend/app/modules`、`backend/app/core`、`frontend/src`、`docs/`  \n',
    '**稽核執行者：** AI Assistant (Cursor)\n',
    '\n',
    '---\n',
    '\n',
    '## 目錄\n',
    '\n',
    '1. [時間來源一致性](#1-時間來源一致性)\n',
    '2. [業務日期歸屬邏輯](#2-業務日期歸屬邏輯)\n',
    '3. [報表查詢安全性](#3-報表查詢安全性)\n',
    '4. [Schema 一致性審查](#4-schema-一致性審查)\n',
    '5. [前端時間處理](#5-前端時間處理)\n',
    '6. [文件 vs 程式碼一致性](#6-文件-vs-程式碼一致性)\n',
    '7. [風險彙總 (P0 / P1 / P2)](#7-風險彙總)\n',
    '\n',
    '---\n',
    '\n',
    '## 1. 時間來源一致性\n',
    '\n',
    '### 1.1 Production 程式碼掃描（排除 .bak / .backup / tests/）\n',
    '\n',
    '#### 安全項目\n',
    '\n',
    '| 檔案 | 行號 | 程式碼 | 風險等級 | 說明 |\n',
    '|------|------|--------|----------|------|\n',
    '| `backend/app/modules/attendance/repo.py` | 31 | `return datetime.now(timezone.utc)` | SAFE | timezone-aware UTC，符合規範 |\n',
    '| `backend/app/core/config.py` | 30 | `return datetime.now(timezone.utc)` | SAFE | `get_utc_now()` helper，正確 |\n',
    '\n',
    '#### 風險項目\n',
    '\n',
    '| 檔案 | 行號 | 程式碼 | 風險等級 | 說明 |\n',
    '|------|------|--------|----------|------|\n',
    '| `policy_engine.py` | 57–58 | `datetime.combine(datetime.today(), self.start_time)` | **P1** | `datetime.today()` 回傳 naive local datetime，若 server 時區非 UTC+8 則 WorkWindow.duration_minutes() 計算結果誤差 |\n',
    '| `policy_engine.py` | 430 | `expected_start = expected_start.replace(tzinfo=punch_in_time.tzinfo)` | **P1** | `.replace(tzinfo=...)` 只標記時區不做時刻轉換。若 punch_in_time 為 UTC，work_start_time 基準被錯誤解讀為 UTC 而非 Asia/Taipei，遲到判斷誤差最高 8 小時 |\n',
    '| `policy_engine.py` | 465 | `expected_end = expected_end.replace(tzinfo=punch_out_time.tzinfo)` | **P1** | 同上，影響早退判斷 |\n',
    '| `policy_engine.py` | 637–638 | `window_start/end_dt.replace(tzinfo=punch_in_time.tzinfo)` | **P1** | 同上，影響 WorkWindow 有效工時計算 |\n',
    '\n',
    '**`.replace()` vs `.astimezone()` 差異說明：**\n',
    '\n',
    '```\n',
    '# 錯誤（目前做法）：標記時區但不轉換時刻\n',
    '# expected_start.replace(tzinfo=UTC) 使 work_start_time 被視為 UTC 08:00 → Taipei 16:00（偏差 8 小時）\n',
    '\n',
    '# 正確做法：先以 Taipei 日期組合，再標記 Taipei 時區\n',
    '# business_date = punch_in_time.astimezone(TZ_TAIPEI).date()\n',
    '# expected_start = datetime.combine(business_date, work_start_time).replace(tzinfo=TZ_TAIPEI)\n',
    '# 結果：work_start_time = Taipei 08:00 → UTC 00:00（正確）\n',
    '```\n',
    '\n',
    '### 1.2 測試程式碼掃描（informational）\n',
    '\n',
    '| 檔案 | 出現次數 | 風險說明 |\n',
    '|------|----------|----------|\n',
    '| `tests/test_business_invariant.py` | 13 處 `datetime.utcnow()` | naive UTC，與 TIMESTAMPTZ column 比對可能引發 tz-aware 衝突 |\n',
    '| `tests/test_model_constraints.py` | 14 處 `datetime.utcnow()` | 同上 |\n',
    '\n',
    '### 1.3 其他模組（超出 attendance 核心範圍，informational）\n',
    '\n',
    '| 模組 | 問題 | 建議 |\n',
    '|------|------|------|\n',
    '| `modules/tenants/models.py` | `default=datetime.utcnow`（naive） | 改為 `server_default=text(\'NOW()')` 或 `default=get_utc_now` |\n',
    '| `modules/auth/models.py` | 多處 `default=datetime.utcnow` | 同上 |\n',
    '| `modules/audit/models.py`、`service.py` | `datetime.utcnow()` | 同上 |\n',
    '| `core/security/jwt.py` | `now = datetime.utcnow()` | 改為 `datetime.now(timezone.utc)` |\n',
    '\n',
    '---\n',
    '\n',
    '## 2. 業務日期歸屬邏輯\n',
    '\n',
    '### 2.1 文件定義規則（SA_MODULE_SPEC_v2.1.md §29）\n',
    '\n',
    '- session 所屬日期 = `punch_in_time` 的 Asia/Taipei 業務時區日期\n',
    '- 月報所屬月份 = session 的 Asia/Taipei `punch_in_time` 所在月份\n',
    '- 若 session 跨月，整體歸屬於 `punch_in_time` 所在月份\n',
    '- `raw_duration = punch_out_time - punch_in_time`（UTC 減法，天然支援跨午夜）\n',
    '\n',
    '### 2.2 跨午夜場景驗證\n',
    '\n',
    '**場景 A（指定測試情境）：**\n',
    '\n',
    '```\n',
    'punch_in  : 2026-03-31 23:00 Asia/Taipei  →  2026-03-31 15:00 UTC\n',
    'punch_out : 2026-04-01 02:00 Asia/Taipei  →  2026-03-31 18:00 UTC\n',
    '```\n',
    '\n',
    '| 問題 | 預期 | 程式碼行為 | 符合？ |\n',
    '|------|------|-----------|--------|\n',
    '| Session 歸屬日期 | **March 31** | 無 `session_date` 欄位，須應用層計算 | 部分（邏輯正確但欄位缺失） |\n',
    '| `duration_minutes` | 180 分鐘 | (18:00 UTC − 15:00 UTC) = 180 | OK |\n',
    '| `check_late` 基準日期 | 2026-03-31（Taipei） | `punch_in_time.date()` → 2026-03-31（UTC 恰好相同） | 此例巧合正確 |\n',
    '\n',
    '**場景 B（高風險：Asia/Taipei 00:00~07:59 打卡）：**\n',
    '\n',
    '```\n',
    'punch_in  : 2026-03-12 00:30 Asia/Taipei  →  2026-03-11 16:30 UTC\n',
    '```\n',
    '\n',
    '| 問題 | 預期 | 程式碼行為 | 符合？ |\n',
    '|------|------|-----------|--------|\n',
    '| Session 所屬日期 | 2026-03-12 | 須應用層計算，目前未實作 | 未實作 |\n',
    '| `check_late` 基準日期 | 2026-03-12（Taipei） | `punch_in_time.date()` → **2026-03-11**（UTC） | 偏差 1 天 |\n',
    '\n',
    '**結論：** `policy_engine.py` 在 Asia/Taipei 00:00~07:59 打卡的 session，遲到/早退判斷基準日期將錯誤偏移 1 天。原因是程式碼使用 `punch_in_time.date()`（UTC 日期）而非 `punch_in_time.astimezone(TZ_TAIPEI).date()`（Taipei 日期）。\n',
    '\n',
    '### 2.3 程式碼路徑清單\n',
    '\n',
    '| 路徑 | 使用的日期欄位 | 問題 |\n',
    '|------|--------------|------|\n',
    '| `policy_engine.py:424` `check_late()` | `punch_in_time.date()` UTC | 應改為 `punch_in_time.astimezone(TZ_TAIPEI).date()` |\n',
    '| `policy_engine.py:459` `check_early_leave()` | `punch_out_time.date()` UTC | 同上 |\n',
    '| `policy_engine.py:627,631` `_calculate_effective_work()` | `punch_in_time.date()` UTC | 同上 |\n',
    '| `repo.py` `get_sessions()` | 無日期過濾 | 安全 |\n',
    '| 報表查詢（WP-11-06） | 未實作 | 預防性風險 |\n',
    '\n',
    '---\n',
    '\n',
    '## 3. 報表查詢安全性\n',
    '\n',
    '### 3.1 危險模式掃描結果\n',
    '\n',
    '搜尋範圍：`backend/app/modules/attendance/`（排除 .bak / .backup）\n',
    '\n',
    '| 模式 | 結果 |\n',
    '|------|------|\n',
    '| `DATE(` | 未發現 |\n',
    '| `EXTRACT(` | 未發現 |\n',
    '| `CAST(` | 未發現 |\n',
    '| `punch_out_time BETWEEN` | 未發現 |\n',
    '| `func.date(` | 未發現 |\n',
    '| `strftime` | 未發現 |\n',
    '| `date_trunc` | 未發現 |\n',
    '\n',
    '**現階段結論：目前 production 無任何危險查詢模式。**\n',
    '\n',
    '### 3.2 現有查詢索引安全性\n',
    '\n',
    '| 端點 / 方法 | 查詢條件 | 命中索引 | 安全 |\n',
    '|------------|---------|----------|------|\n',
    '| `GET /history` → `get_sessions()` | `company_id + user_id` | `idx_sessions_company_user` | OK |\n',
    '| `GET /history` 排序 | `ORDER BY punch_in_time DESC` | `idx_sessions_company_punch_in` | OK |\n',
    '| `GET /status` → `get_open_session()` | `company_id + user_id + status=open` | `uq_sessions_company_user_open`（partial） | OK |\n',
    '| `get_recent_checkpoint()` | `company_id + user_id + punch_time >= cutoff` | `idx_checkpoints_company_user_time` | OK |\n',
    '\n',
    '### 3.3 AttendanceHistoryRequest Schema vs 實作不一致\n',
    '\n',
    '`schemas.py:154-159` 定義了 `start_date`/`end_date` 過濾參數，但 `repo.get_sessions()` 及 API endpoint **均未實作**這些參數。\n',
    '\n',
    'P1 風險：未來補實作時，若開發者未遵循 UTC boundary 模式，極易引入 `DATE()` 函數或 `punch_out_time BETWEEN` 危險查詢。\n',
    '\n',
    '### 3.4 punch_out_time 三重危險（預防性）\n',
    '\n',
    '若未來有人以 `punch_out_time` 進行報表查詢：\n',
    '\n',
    '1. **NULL 風險：** open session 的 `punch_out_time` 為 NULL，`BETWEEN`/`>=` 會靜默排除。\n',
    '2. **語義錯誤：** 跨午夜 session 應歸屬 punch_in 日期，用 punch_out 日期會誤分類。\n',
    '3. **無索引：** `attendance_sessions` 無 `punch_out_time` 索引，全表掃描。\n',
    '\n',
    '### 3.5 推薦查詢模式\n',
    '\n',
    '```python\n',
    '# 正確：以 Asia/Taipei 計算月份邊界，轉 UTC 後直接比較 indexed column\n',
    'from zoneinfo import ZoneInfo\n',
    'TZ_TAIPEI = ZoneInfo("Asia/Taipei")\n',
    'month_start_utc = datetime(year, month, 1, tzinfo=TZ_TAIPEI).astimezone(timezone.utc)\n',
    'month_end_utc   = datetime(year, month + 1, 1, tzinfo=TZ_TAIPEI).astimezone(timezone.utc)\n',
    '# WHERE company_id = ? AND punch_in_time >= month_start_utc AND punch_in_time < month_end_utc\n',
    '# 命中 idx_sessions_company_punch_in，Index Range Scan\n',
    '```\n',
    '\n',
    '---\n',
    '\n',
    '## 4. Schema 一致性審查\n',
    '\n',
    '### 4.1 Timestamp 型別一致性\n',
    '\n',
    '| 表 | 欄位 | SQLAlchemy | Migration | PostgreSQL 型別 | 符合規範 |\n',
    '|----|------|-----------|-----------|-----------------|----------|\n',
    '| `attendance_sessions` | `punch_in_time` | `DateTime(timezone=True)` | `sa.DateTime(timezone=True)` | TIMESTAMPTZ | OK |\n',
    '| `attendance_sessions` | `punch_out_time` | `DateTime(timezone=True)` | `sa.DateTime(timezone=True)` | 